language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
addons:
  apt:
    packages:
    - git
    - make
    - curl
    - xz-utils
    - file
    - pandoc
    - libboost-all-dev
    - ibus-mozc
    - gcc-5
    - g++-5
    - build-essential
    sources:
    - ubuntu-toolchain-r-test
before_install:
  - sudo apt-get update -qq
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 1
  - mkdir ./target
  - export CC="gcc-5"
  - export CXX="g++-5"
  - export CFLAGS=-std=c++11
  - export CXXFLAGS=-std=c++11
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install numpy scipy scikit-learn Cython
  - python --version
  - python setup.py install
  - pip install coveralls coverage nose pypandoc
script:
  - python setup.py test
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - kensuke.mit@gmail.com
    on_success: always
    on_failure: always